//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int Instructorid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Office { get; set; }
        public string Courses { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> Courseid { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
